AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

require:
  - rubocop-rake
  - rubocop-rspec

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false